### ISSUE TITLE
 Script stopping problem

### ISSUE THREAD

**Issue by Raven87800** [newerton/bombcrypto-bot#130]
Hello,

From time to time, the script stops and displays the attached message.
Where can the problem come from?
Moreover, with multi-account, is it possible to prevent the windows from going full screen in order to be able to perform the different actions?

Thanking you,

Good day,

Cordially,

PS: Thanks for sharing the script
![Capturecpt](https://user-images.githubusercontent.com/103002910/161639038-66e89647-d5e1-4766-94c9-0edbab20b897.PNG)
.

**Comment by newerton** [comment]
@Raven87800 Hi,

How many accounts do you have using the bot? How many GB of memory do you have? The error occurred because the bot was unable to make one of the windows "active".

About letting the bot work side by side, there's no way, why does the bot do image recognition, if the bot recognizes that it has 4 equal buttons (4 accounts), which one will it click?

That's why the bot maximizes and then minimizes, one by one.

What you can do is leave the screens separate on the monitor, and the bot will maximize, do the actions, and then return the window to the same position as before.
