### ISSUE TITLE
a problem in game recent

### ISSUE THREAD

**Issue by agsfmlcx** [newerton/bombcrypto-bot#52]
In the end, there will be only one normal obstacle on the map, but it will not disappear no matter how you blow it up, even if you re-enter the map. After refreshing the browser and re-entering the game, it will switch to a new map. Obviously this is a bug in the game, but hopefully this situation can be taken into account. Because it might waste a lot of time if you don't find out.

**Comment by newerton** [comment]
I can't do this implementation in the bot, because it's a game bug that needs to be fixed.

But you can add a refresh command, after the bot gets your heroes to put on the map.

Go to ./src/heroes.py on line 102, and add:

`pyautogui.hotkey('ctrl', 'shift', 'r')`

![image](https://user-images.githubusercontent.com/4175945/150534206-378e322b-2bd9-4edf-aecb-7dbda057f25e.png)
